# coding: utf-8

"""
    NLD2 API

    The <b>NLD2 API</b> is a complete, programmable interface to all National Levee Database functionality. The NLD2 API is a RESTful web service, using standard technologies like HTTP verbs, headers, and status codes.<br/><br/>The <a href=\"/#/\" target=\"_blank\">National Levee Database website</a> is built on this API, and all of its services are available for integration into your application. To get started, we recommend exploring the website to learn about the functionality that is available and then using the OpenAPI specification below to try connecting to the test/hello endpoint.<br/><br/>Currently, you can develop your application with the public API. For more advanced features, you may need an NLD account and specific government clearance, depending on the nature of the data. If you need assistance, please email us at <a href=\"mailto:NLD@usace.army.mil\">NLD@usace.army.mil</a> or call us at <a href=\"tel:18775383387\">1-877-LEVEEUS</a> (1-877-538-3387).  # noqa: E501

    OpenAPI spec version: 3.26.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.system_legacy_api import SystemLegacyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestSystemLegacyApi(unittest.TestCase):
    """SystemLegacyApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.system_legacy_api.SystemLegacyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_deprecated_api_system_id_features_leveed_areas_get(self):
        """Test case for deprecated_api_system_id_features_leveed_areas_get

        """
        pass

    def test_get_all_high_level_risk_assessments_by_id(self):
        """Test case for get_all_high_level_risk_assessments_by_id

        """
        pass

    def test_system_advanced_fields_get(self):
        """Test case for system_advanced_fields_get

        """
        pass

    def test_system_field_values_field_get(self):
        """Test case for system_field_values_field_get

        """
        pass

    def test_system_id_detail_get(self):
        """Test case for system_id_detail_get

        """
        pass

    def test_system_id_embankment_sections_get(self):
        """Test case for system_id_embankment_sections_get

        """
        pass

    def test_system_id_fema_segments_get(self):
        """Test case for system_id_fema_segments_get

        """
        pass

    def test_system_id_route_get(self):
        """Test case for system_id_route_get

        """
        pass

    def test_system_suggestions_post(self):
        """Test case for system_suggestions_post

        """
        pass

    def test_system_systems_post(self):
        """Test case for system_systems_post

        """
        pass


if __name__ == '__main__':
    unittest.main()
