# coding: utf-8

"""
    NLD2 API

    The <b>NLD2 API</b> is a complete, programmable interface to all National Levee Database functionality. The NLD2 API is a RESTful web service, using standard technologies like HTTP verbs, headers, and status codes.<br/><br/>The <a href=\"/#/\" target=\"_blank\">National Levee Database website</a> is built on this API, and all of its services are available for integration into your application. To get started, we recommend exploring the website to learn about the functionality that is available and then using the OpenAPI specification below to try connecting to the test/hello endpoint.<br/><br/>Currently, you can develop your application with the public API. For more advanced features, you may need an NLD account and specific government clearance, depending on the nature of the data. If you need assistance, please email us at <a href=\"mailto:NLD@usace.army.mil\">NLD@usace.army.mil</a> or call us at <a href=\"tel:18775383387\">1-877-LEVEEUS</a> (1-877-538-3387).  # noqa: E501

    OpenAPI spec version: 3.26.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.risk_api import RiskApi  # noqa: E501
from swagger_client.rest import ApiException


class TestRiskApi(unittest.TestCase):
    """RiskApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.risk_api.RiskApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_consequences_post(self):
        """Test case for consequences_post

        """
        pass

    def test_get_all_risk_driver_mitigations(self):
        """Test case for get_all_risk_driver_mitigations

        """
        pass

    def test_get_all_risk_drivers(self):
        """Test case for get_all_risk_drivers

        """
        pass

    def test_get_all_risk_process_links(self):
        """Test case for get_all_risk_process_links

        """
        pass

    def test_get_all_system_screenings(self):
        """Test case for get_all_system_screenings

        """
        pass

    def test_high_level_risk_assessment_id_get(self):
        """Test case for high_level_risk_assessment_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
