# coding: utf-8

"""
    NLD2 API

    The <b>NLD2 API</b> is a complete, programmable interface to all National Levee Database functionality. The NLD2 API is a RESTful web service, using standard technologies like HTTP verbs, headers, and status codes.<br/><br/>The <a href=\"/#/\" target=\"_blank\">National Levee Database website</a> is built on this API, and all of its services are available for integration into your application. To get started, we recommend exploring the website to learn about the functionality that is available and then using the OpenAPI specification below to try connecting to the test/hello endpoint.<br/><br/>Currently, you can develop your application with the public API. For more advanced features, you may need an NLD account and specific government clearance, depending on the nature of the data. If you need assistance, please email us at <a href=\"mailto:NLD@usace.army.mil\">NLD@usace.army.mil</a> or call us at <a href=\"tel:18775383387\">1-877-LEVEEUS</a> (1-877-538-3387).  # noqa: E501

    OpenAPI spec version: 3.26.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.features_api import FeaturesApi  # noqa: E501
from swagger_client.rest import ApiException


class TestFeaturesApi(unittest.TestCase):
    """FeaturesApi unit test stubs"""

    def setUp(self):
        self.api = swagger_client.api.features_api.FeaturesApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_boreholes_id_get(self):
        """Test case for boreholes_id_get

        """
        pass

    def test_centerlines_id_get(self):
        """Test case for centerlines_id_get

        """
        pass

    def test_channels_id_get(self):
        """Test case for channels_id_get

        """
        pass

    def test_closure_structures_id_get(self):
        """Test case for closure_structures_id_get

        """
        pass

    def test_cross_sections_id_get(self):
        """Test case for cross_sections_id_get

        """
        pass

    def test_floodwalls_id_get(self):
        """Test case for floodwalls_id_get

        """
        pass

    def test_frm_lines_id_get(self):
        """Test case for frm_lines_id_get

        """
        pass

    def test_geometries_type_id_get(self):
        """Test case for geometries_type_id_get

        """
        pass

    def test_get_alignment_line(self):
        """Test case for get_alignment_line

        """
        pass

    def test_get_all_alignment_lines(self):
        """Test case for get_all_alignment_lines

        """
        pass

    def test_get_all_boreholes(self):
        """Test case for get_all_boreholes

        """
        pass

    def test_get_all_channels(self):
        """Test case for get_all_channels

        """
        pass

    def test_get_all_closure_structures(self):
        """Test case for get_all_closure_structures

        """
        pass

    def test_get_all_cross_sections(self):
        """Test case for get_all_cross_sections

        """
        pass

    def test_get_all_floodwalls(self):
        """Test case for get_all_floodwalls

        """
        pass

    def test_get_all_frm_lines(self):
        """Test case for get_all_frm_lines

        """
        pass

    def test_get_all_gravity_drains(self):
        """Test case for get_all_gravity_drains

        """
        pass

    def test_get_all_levee_centerlines(self):
        """Test case for get_all_levee_centerlines

        """
        pass

    def test_get_all_levee_crossings(self):
        """Test case for get_all_levee_crossings

        """
        pass

    def test_get_all_levee_stations(self):
        """Test case for get_all_levee_stations

        """
        pass

    def test_get_all_leveed_areas(self):
        """Test case for get_all_leveed_areas

        """
        pass

    def test_get_all_piezometers(self):
        """Test case for get_all_piezometers

        """
        pass

    def test_get_all_pipe_gates(self):
        """Test case for get_all_pipe_gates

        """
        pass

    def test_get_all_pipes(self):
        """Test case for get_all_pipes

        """
        pass

    def test_get_all_pump_stations(self):
        """Test case for get_all_pump_stations

        """
        pass

    def test_get_all_relief_wells(self):
        """Test case for get_all_relief_wells

        """
        pass

    def test_get_all_toedrains(self):
        """Test case for get_all_toedrains

        """
        pass

    def test_get_geo_json_feature_collection(self):
        """Test case for get_geo_json_feature_collection

        """
        pass

    def test_get_geo_json_feature_collection_0(self):
        """Test case for get_geo_json_feature_collection_0

        """
        pass

    def test_get_some(self):
        """Test case for get_some

        """
        pass

    def test_gravity_drains_id_get(self):
        """Test case for gravity_drains_id_get

        """
        pass

    def test_levee_crossings_id_get(self):
        """Test case for levee_crossings_id_get

        """
        pass

    def test_levee_stations_id_get(self):
        """Test case for levee_stations_id_get

        """
        pass

    def test_leveed_areas_id_get(self):
        """Test case for leveed_areas_id_get

        """
        pass

    def test_piezometers_id_get(self):
        """Test case for piezometers_id_get

        """
        pass

    def test_pipe_gates_id_get(self):
        """Test case for pipe_gates_id_get

        """
        pass

    def test_pipes_id_get(self):
        """Test case for pipes_id_get

        """
        pass

    def test_pump_stations_id_get(self):
        """Test case for pump_stations_id_get

        """
        pass

    def test_relief_wells_id_get(self):
        """Test case for relief_wells_id_get

        """
        pass

    def test_toedrains_id_get(self):
        """Test case for toedrains_id_get

        """
        pass


if __name__ == '__main__':
    unittest.main()
