# coding: utf-8

"""
    NLD2 API

    The <b>NLD2 API</b> is a complete, programmable interface to all National Levee Database functionality. The NLD2 API is a RESTful web service, using standard technologies like HTTP verbs, headers, and status codes.<br/><br/>The <a href=\"/#/\" target=\"_blank\">National Levee Database website</a> is built on this API, and all of its services are available for integration into your application. To get started, we recommend exploring the website to learn about the functionality that is available and then using the OpenAPI specification below to try connecting to the test/hello endpoint.<br/><br/>Currently, you can develop your application with the public API. For more advanced features, you may need an NLD account and specific government clearance, depending on the nature of the data. If you need assistance, please email us at <a href=\"mailto:NLD@usace.army.mil\">NLD@usace.army.mil</a> or call us at <a href=\"tel:18775383387\">1-877-LEVEEUS</a> (1-877-538-3387).  # noqa: E501

    OpenAPI spec version: 3.26.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class HighLevelRiskAssessment1(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'financial_risk': 'float',
        'people_at_risk': 'float',
        'structures_at_risk': 'float'
    }

    attribute_map = {
        'financial_risk': 'financialRisk',
        'people_at_risk': 'peopleAtRisk',
        'structures_at_risk': 'structuresAtRisk'
    }

    def __init__(self, financial_risk=None, people_at_risk=None, structures_at_risk=None, _configuration=None):  # noqa: E501
        """HighLevelRiskAssessment1 - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._financial_risk = None
        self._people_at_risk = None
        self._structures_at_risk = None
        self.discriminator = None

        if financial_risk is not None:
            self.financial_risk = financial_risk
        if people_at_risk is not None:
            self.people_at_risk = people_at_risk
        if structures_at_risk is not None:
            self.structures_at_risk = structures_at_risk

    @property
    def financial_risk(self):
        """Gets the financial_risk of this HighLevelRiskAssessment1.  # noqa: E501


        :return: The financial_risk of this HighLevelRiskAssessment1.  # noqa: E501
        :rtype: float
        """
        return self._financial_risk

    @financial_risk.setter
    def financial_risk(self, financial_risk):
        """Sets the financial_risk of this HighLevelRiskAssessment1.


        :param financial_risk: The financial_risk of this HighLevelRiskAssessment1.  # noqa: E501
        :type: float
        """

        self._financial_risk = financial_risk

    @property
    def people_at_risk(self):
        """Gets the people_at_risk of this HighLevelRiskAssessment1.  # noqa: E501


        :return: The people_at_risk of this HighLevelRiskAssessment1.  # noqa: E501
        :rtype: float
        """
        return self._people_at_risk

    @people_at_risk.setter
    def people_at_risk(self, people_at_risk):
        """Sets the people_at_risk of this HighLevelRiskAssessment1.


        :param people_at_risk: The people_at_risk of this HighLevelRiskAssessment1.  # noqa: E501
        :type: float
        """

        self._people_at_risk = people_at_risk

    @property
    def structures_at_risk(self):
        """Gets the structures_at_risk of this HighLevelRiskAssessment1.  # noqa: E501


        :return: The structures_at_risk of this HighLevelRiskAssessment1.  # noqa: E501
        :rtype: float
        """
        return self._structures_at_risk

    @structures_at_risk.setter
    def structures_at_risk(self, structures_at_risk):
        """Sets the structures_at_risk of this HighLevelRiskAssessment1.


        :param structures_at_risk: The structures_at_risk of this HighLevelRiskAssessment1.  # noqa: E501
        :type: float
        """

        self._structures_at_risk = structures_at_risk

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(HighLevelRiskAssessment1, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, HighLevelRiskAssessment1):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, HighLevelRiskAssessment1):
            return True

        return self.to_dict() != other.to_dict()
