# coding: utf-8

"""
    NLD2 API

    The <b>NLD2 API</b> is a complete, programmable interface to all National Levee Database functionality. The NLD2 API is a RESTful web service, using standard technologies like HTTP verbs, headers, and status codes.<br/><br/>The <a href=\"/#/\" target=\"_blank\">National Levee Database website</a> is built on this API, and all of its services are available for integration into your application. To get started, we recommend exploring the website to learn about the functionality that is available and then using the OpenAPI specification below to try connecting to the test/hello endpoint.<br/><br/>Currently, you can develop your application with the public API. For more advanced features, you may need an NLD account and specific government clearance, depending on the nature of the data. If you need assistance, please email us at <a href=\"mailto:NLD@usace.army.mil\">NLD@usace.army.mil</a> or call us at <a href=\"tel:18775383387\">1-877-LEVEEUS</a> (1-877-538-3387).  # noqa: E501

    OpenAPI spec version: 3.26.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class Metrics(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'type': 'str',
        'key_type': 'str',
        'value': 'MetricsaccreditationstatusValue',
        'order': 'int',
        'display': 'str',
        'x_axis_label': 'int',
        'y_axis_label': 'str'
    }

    attribute_map = {
        'name': 'name',
        'type': 'type',
        'key_type': 'keyType',
        'value': 'value',
        'order': 'order',
        'display': 'display',
        'x_axis_label': 'xAxisLabel',
        'y_axis_label': 'yAxisLabel'
    }

    def __init__(self, name=None, type=None, key_type=None, value=None, order=None, display=None, x_axis_label=None, y_axis_label=None, _configuration=None):  # noqa: E501
        """Metrics - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._name = None
        self._type = None
        self._key_type = None
        self._value = None
        self._order = None
        self._display = None
        self._x_axis_label = None
        self._y_axis_label = None
        self.discriminator = None

        if name is not None:
            self.name = name
        if type is not None:
            self.type = type
        if key_type is not None:
            self.key_type = key_type
        if value is not None:
            self.value = value
        if order is not None:
            self.order = order
        if display is not None:
            self.display = display
        if x_axis_label is not None:
            self.x_axis_label = x_axis_label
        if y_axis_label is not None:
            self.y_axis_label = y_axis_label

    @property
    def name(self):
        """Gets the name of this Metrics.  # noqa: E501


        :return: The name of this Metrics.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this Metrics.


        :param name: The name of this Metrics.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def type(self):
        """Gets the type of this Metrics.  # noqa: E501


        :return: The type of this Metrics.  # noqa: E501
        :rtype: str
        """
        return self._type

    @type.setter
    def type(self, type):
        """Sets the type of this Metrics.


        :param type: The type of this Metrics.  # noqa: E501
        :type: str
        """

        self._type = type

    @property
    def key_type(self):
        """Gets the key_type of this Metrics.  # noqa: E501


        :return: The key_type of this Metrics.  # noqa: E501
        :rtype: str
        """
        return self._key_type

    @key_type.setter
    def key_type(self, key_type):
        """Sets the key_type of this Metrics.


        :param key_type: The key_type of this Metrics.  # noqa: E501
        :type: str
        """

        self._key_type = key_type

    @property
    def value(self):
        """Gets the value of this Metrics.  # noqa: E501


        :return: The value of this Metrics.  # noqa: E501
        :rtype: MetricsaccreditationstatusValue
        """
        return self._value

    @value.setter
    def value(self, value):
        """Sets the value of this Metrics.


        :param value: The value of this Metrics.  # noqa: E501
        :type: MetricsaccreditationstatusValue
        """

        self._value = value

    @property
    def order(self):
        """Gets the order of this Metrics.  # noqa: E501


        :return: The order of this Metrics.  # noqa: E501
        :rtype: int
        """
        return self._order

    @order.setter
    def order(self, order):
        """Sets the order of this Metrics.


        :param order: The order of this Metrics.  # noqa: E501
        :type: int
        """

        self._order = order

    @property
    def display(self):
        """Gets the display of this Metrics.  # noqa: E501


        :return: The display of this Metrics.  # noqa: E501
        :rtype: str
        """
        return self._display

    @display.setter
    def display(self, display):
        """Sets the display of this Metrics.


        :param display: The display of this Metrics.  # noqa: E501
        :type: str
        """

        self._display = display

    @property
    def x_axis_label(self):
        """Gets the x_axis_label of this Metrics.  # noqa: E501


        :return: The x_axis_label of this Metrics.  # noqa: E501
        :rtype: int
        """
        return self._x_axis_label

    @x_axis_label.setter
    def x_axis_label(self, x_axis_label):
        """Sets the x_axis_label of this Metrics.


        :param x_axis_label: The x_axis_label of this Metrics.  # noqa: E501
        :type: int
        """

        self._x_axis_label = x_axis_label

    @property
    def y_axis_label(self):
        """Gets the y_axis_label of this Metrics.  # noqa: E501


        :return: The y_axis_label of this Metrics.  # noqa: E501
        :rtype: str
        """
        return self._y_axis_label

    @y_axis_label.setter
    def y_axis_label(self, y_axis_label):
        """Sets the y_axis_label of this Metrics.


        :param y_axis_label: The y_axis_label of this Metrics.  # noqa: E501
        :type: str
        """

        self._y_axis_label = y_axis_label

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Metrics, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Metrics):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, Metrics):
            return True

        return self.to_dict() != other.to_dict()
