# coding: utf-8

"""
    NLD2 API

    The <b>NLD2 API</b> is a complete, programmable interface to all National Levee Database functionality. The NLD2 API is a RESTful web service, using standard technologies like HTTP verbs, headers, and status codes.<br/><br/>The <a href=\"/#/\" target=\"_blank\">National Levee Database website</a> is built on this API, and all of its services are available for integration into your application. To get started, we recommend exploring the website to learn about the functionality that is available and then using the OpenAPI specification below to try connecting to the test/hello endpoint.<br/><br/>Currently, you can develop your application with the public API. For more advanced features, you may need an NLD account and specific government clearance, depending on the nature of the data. If you need assistance, please email us at <a href=\"mailto:NLD@usace.army.mil\">NLD@usace.army.mil</a> or call us at <a href=\"tel:18775383387\">1-877-LEVEEUS</a> (1-877-538-3387).  # noqa: E501

    OpenAPI spec version: 3.26.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""


import pprint
import re  # noqa: F401

import six

from swagger_client.configuration import Configuration


class SearchRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'text': 'str',
        'context_key': 'str',
        'include': 'str'
    }

    attribute_map = {
        'text': 'text',
        'context_key': 'contextKey',
        'include': 'include'
    }

    def __init__(self, text=None, context_key=None, include='all', _configuration=None):  # noqa: E501
        """SearchRequest - a model defined in Swagger"""  # noqa: E501
        if _configuration is None:
            _configuration = Configuration()
        self._configuration = _configuration

        self._text = None
        self._context_key = None
        self._include = None
        self.discriminator = None

        if text is not None:
            self.text = text
        if context_key is not None:
            self.context_key = context_key
        if include is not None:
            self.include = include

    @property
    def text(self):
        """Gets the text of this SearchRequest.  # noqa: E501


        :return: The text of this SearchRequest.  # noqa: E501
        :rtype: str
        """
        return self._text

    @text.setter
    def text(self, text):
        """Sets the text of this SearchRequest.


        :param text: The text of this SearchRequest.  # noqa: E501
        :type: str
        """

        self._text = text

    @property
    def context_key(self):
        """Gets the context_key of this SearchRequest.  # noqa: E501


        :return: The context_key of this SearchRequest.  # noqa: E501
        :rtype: str
        """
        return self._context_key

    @context_key.setter
    def context_key(self, context_key):
        """Sets the context_key of this SearchRequest.


        :param context_key: The context_key of this SearchRequest.  # noqa: E501
        :type: str
        """

        self._context_key = context_key

    @property
    def include(self):
        """Gets the include of this SearchRequest.  # noqa: E501


        :return: The include of this SearchRequest.  # noqa: E501
        :rtype: str
        """
        return self._include

    @include.setter
    def include(self, include):
        """Sets the include of this SearchRequest.


        :param include: The include of this SearchRequest.  # noqa: E501
        :type: str
        """
        allowed_values = ["systems", "segments", "contexts", "all"]  # noqa: E501
        if (self._configuration.client_side_validation and
                include not in allowed_values):
            raise ValueError(
                "Invalid value for `include` ({0}), must be one of {1}"  # noqa: E501
                .format(include, allowed_values)
            )

        self._include = include

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(SearchRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, SearchRequest):
            return False

        return self.to_dict() == other.to_dict()

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        if not isinstance(other, SearchRequest):
            return True

        return self.to_dict() != other.to_dict()
